[project]
name = "asimov-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "pandas>=2.3.1",
    "streamlit>=1.48.0",
    "streamlit-aggrid>=1.1.7",
]
